# basic linting checks on master merge

name: workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Install pyaudio 
      run: |
        sudo apt-get update
        sudo apt-get install python3-pyaudio
        sudo apt-get install portaudio19-dev
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies and activate
      run: | 
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Run make linting checks
      run: |
        ls
        make check
